program DelphiBackendFramework;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  System.SysUtils,
  Container.DependencyDescriptor in 'Source\Core\Container.DependencyDescriptor.pas',
  Container.App in 'Source\Core\Container.App.pas',
  Container.Scope in 'Source\Core\Container.Scope.pas',
  AppExceptions in 'Source\Core\AppExceptions.pas',
  HttpExceptions in 'Source\Http\HttpExceptions.pas',
  Dto.Attributes in 'Source\Dto\Dto.Attributes.pas',
  Dto.Binder.Port in 'Source\Dto\Dto.Binder.Port.pas',
  Dto.Binder in 'Source\Dto\Dto.Binder.pas',
  Dto.Metadata in 'Source\Dto\Dto.Metadata.pas',
  Dto.TypeInspector in 'Source\Dto\Dto.TypeInspector.pas',
  Dto.Validation.Context in 'Source\Dto\Dto.Validation.Context.pas',
  Dto.Validation.BooleanValidator in 'Source\Dto\Dto.Validation.BooleanValidator.pas',
  Dto.Validation.DateValidator in 'Source\Dto\Dto.Validation.DateValidator.pas',
  Dto.Validation.NumberValidator in 'Source\Dto\Dto.Validation.NumberValidator.pas',
  Dto.Validation.RequiredValidator in 'Source\Dto\Dto.Validation.RequiredValidator.pas',
  Dto.Validation.StringValidator in 'Source\Dto\Dto.Validation.StringValidator.pas',
  Http.Controller.Port in 'Source\Http\Http.Controller.Port.pas',
  Http.Middleware.Port in 'Source\Http\Http.Middleware.Port.pas',
  Http.Middleware.Descriptor in 'Source\Http\Http.Middleware.Descriptor.pas',
  Http.Middleware.Attributes in 'Source\Http\Http.Middleware.Attributes.pas',
  Http.Middleware.Pipeline in 'Source\Http\Http.Middleware.Pipeline.pas',
  Http.EndpointAttributeHandler.Port in 'Source\Http\Http.EndpointAttributeHandler.Port.pas',
  Http.Attributes in 'Source\Http\Http.Attributes.pas',
  Http.Cookies in 'Source\Http\Http.Cookies.pas',
  Http.Core in 'Source\Http\Http.Core.pas',
  Http.Context in 'Source\Http\Http.Context.pas',
  Http.RouteDescriptor in 'Source\Http\Http.RouteDescriptor.pas',
  Http.Router.Port in 'Source\Http\Http.Router.Port.pas',
  Http.ControllerScanner in 'Source\Http\Http.ControllerScanner.pas',
  Http.ActionInvoker.Port in 'Source\Http\Http.ActionInvoker.Port.pas',
  Http.Router in 'Source\Http\Http.Router.pas',
  Http.ActionInvoker in 'Source\Http\Http.ActionInvoker.pas',
  Http.Server in 'Source\Http\Http.Server.pas',
  Http.Parameter.Attributes in 'Source\Http\Http.Parameter.Attributes.pas',
  Http.Parameter.Binding in 'Source\Http\Http.Parameter.Binding.pas',
  Http.ParameterDescriptor in 'Source\Http\Http.ParameterDescriptor.pas',
  Http.ActionMetadata in 'Source\Http\Http.ActionMetadata.pas',
  Http.ValueConverter in 'Source\Http\Http.ValueConverter.pas',
  Http.BodyBinder.Port in 'Source\Http\Http.BodyBinder.Port.pas',
  Http.ParameterBinder.Port in 'Source\Http\Http.ParameterBinder.Port.pas',
  Http.BodyBinder in 'Source\Http\Http.BodyBinder.pas',
  Http.ParameterBinder in 'Source\Http\Http.ParameterBinder.pas',
  Http.Composition in 'Source\Http\Http.Composition.pas',
  Env.Helpers in 'Source\Core\Env.Helpers.pas',
  Json.Helpers in 'Source\Core\Json.Helpers.pas',
  Path.Helpers in 'Source\Core\Path.Helpers.pas',
  RttiAttribute.Helpers in 'Source\Core\RttiAttribute.Helpers.pas',
  Options.Port in 'Source\Core\Options.Port.pas',
  Logger.Port in 'Example\Common\Ports\Logger.Port.pas',
  Logger.Options in 'Example\Infrastructure\Logging\Logger.Options.pas',
  Logger in 'Example\Infrastructure\Logging\Logger.pas',
  App.Options in 'Source\Core\App.Options.pas',
  App.Options.Loader in 'Source\Core\App.Options.Loader.pas',
  Root.Controller in 'Example\Presentation\Controllers\Root.Controller.pas',
  Jwt.Entity in 'Example\Domain\Jwt.Entity.pas',
  Role in 'Example\Domain\Role.pas',
  Bootstrap in 'Example\Bootstrap.pas',
  Dto.Binder.Context in 'Source\Dto\Dto.Binder.Context.pas',
  Dto.Port in 'Source\Dto\Dto.Port.pas',
  SignIn.Request.Dto in 'Example\Presentation\Contracts\SignIn.Request.Dto.pas',
  SignIn.Response.Dto in 'Example\Presentation\Contracts\SignIn.Response.Dto.pas',
  SignIn.UseCase in 'Example\Application\UseCases\SignIn.UseCase.pas',
  SignIn.UseCase.Port in 'Example\Application\Ports\SignIn.UseCase.Port.pas',
  ActivateReport.UseCase.Port in 'Example\Application\Ports\ActivateReport.UseCase.Port.pas',
  DeactivateReport.UseCase.Port in 'Example\Application\Ports\DeactivateReport.UseCase.Port.pas',
  DeactivateReport.UseCase in 'Example\Application\UseCases\DeactivateReport.UseCase.pas',
  ActivateReport.UseCase in 'Example\Application\UseCases\ActivateReport.UseCase.pas',
  ActivateReport.Dto in 'Example\Presentation\Contracts\ActivateReport.Dto.pas',
  DeactivateReport.Dto in 'Example\Presentation\Contracts\DeactivateReport.Dto.pas',
  Success.Dto in 'Example\Presentation\Contracts\Success.Dto.pas',
  Utils.Controller in 'Example\Presentation\Controllers\Utils.Controller.pas',
  Jwt.Service.Port in 'Example\Application\Ports\Jwt.Service.Port.pas',
  Http.Server.Options in 'Source\Http\Http.Server.Options.pas',
  Options.Registry in 'Source\Core\Options.Registry.pas',
  Dependency.Attributes in 'Source\Core\Dependency.Attributes.pas',
  Pui.Port in 'Example\Application\Ports\Pui.Port.pas',
  Report.Dto in 'Example\Application\Contracts\Report.Dto.pas',
  Match.Dto in 'Example\Application\Contracts\Match.Dto.pas',
  Event.Dto in 'Example\Application\Contracts\Event.Dto.pas',
  Pui in 'Example\Infrastructure\Pui\Pui.pas',
  Pui.Options in 'Example\Infrastructure\Pui\Pui.Options.pas',
  PuiSignIn.Dto in 'Example\Infrastructure\Pui\Contracts\PuiSignIn.Dto.pas',
  CustomExceptions in 'Example\Common\Exceptions\CustomExceptions.pas',
  FinalizeSearch.Dto in 'Example\Application\Contracts\FinalizeSearch.Dto.pas';

begin
  try
    TBootstrap.Create;
  except
    on Error: Exception do
      Writeln(Error.ClassName, ': ', Error.Message);
  end;
end.
